server:
  port: 8081

security:
  basic:
    enabled: true
  ignored: /ignored, /**/favicon.ico
  cas:
    proxy-validation:
      chains:
        - http://localhost:8180, http://localhost:8181
        - - http://localhost:8280
          - http://localhost:8281
    server:
      base-url: http://localhost:8080/cas/
      protocol-version: 3
    service:
      resolution-mode: dynamic

---

spring:
  profiles: docker

security:
  cas:
    server:
      # Browser/client base url, that uses external exposed port that why is 8082
      base-url: http://localhost:8082/cas/
      # Server-to-server base url, that uses internal docker network so with port mapping that why is 8080
      validation-base-url: http://cas:8080/cas/
    service:
      callback-base-url: http://app:8081/cas/
      paths:
        proxy-callback: /cas/proxy-callback

logging:
  level:
    org.jasig.cas.client.validation: debug


