coverage:
  status:
    project:
      cas-security-spring-boot-autoconfigure:
        paths:
          - "cas-security-spring-boot-autoconfigure/"
        target: auto
      spring-security-cas-extension:
        paths:
          - "spring-security-cas-extension"
        target: auto